packages:
  - apps/*
  - packages/*

overrides:
  js-yaml: 4.3.0
  "fast-uri@>=3.0.0 <4.0.0": 3.1.4
  "fast-uri@>=4.0.0 <5.0.0": 4.1.1
  "find-my-way@>=9.0.0 <10.0.0": 9.7.0

allowBuilds:
  "@swc/core": true
  core-js: true
  esbuild: true
  protobufjs: true
